- hosts: local
  become: No
  tasks:
   - name: Add random publisher host to bootstrap group
     add_host: name="{{ groups['issue_3339_group_2'] | difference(groups['issue_3339_group']) | random }}"  group="issue_3339_group"